-- Constants
-- Contains constant strings for path, message, error message.

local CONSTANT = {}

-- Vim-Vault related
CONSTANT.PROJECT_NAME = "Vim-Vault"


-- File Paths
CONSTANT.FILE_NAME = "vim-vault.json"
CONSTANT.FILE_PATH = "~/" .. CONSTANT.FILE_NAME

CONSTANT.SORT_UNKNOWN = "[S] SORT: UNKNOWN"

CONSTANT.DISPLAY_SMART = "[H] DISPLAY: SMART MODE"
CONSTANT.DISPLAY_FULL = "[H] DISPLAY: FULL PATH"
CONSTANT.DISPLAY_NAME = "[H] DISPLAY: NAME ONLY"

-- VAULT
CONSTANT.VAULT_SORT_NUMBER = "[S] SORT: VAULT NUMBER"
CONSTANT.VAULT_SORT_UPDATED = "[S] SORT: LAST UPDATED"
CONSTANT.VAULT_SORT_PATH = "[S] SORT: FILE PATH"
CONSTANT.VAULT_INSTRUCTIONS_1 = ">> [J] [K] TO NAVIGATE. [ENTER] TO SELECT VAULT. [Q] TO QUIT."
CONSTANT.VAULT_INSTRUCTIONS_2 = ">> [C] TO CREATE NEW VAULT."
CONSTANT.VAULT_INSTRUCTIONS_3 = ">> [M] TO MODIFY VAULT PATH."
CONSTANT.VAULT_INSTRUCTIONS_4 = ">> [D] TO DELETE VAULT."
CONSTANT.VAULT_INSTRUCTIONS_5 = ">> [S] TO TOGGLE SORT MODES, [H] TO TOGGLE DISPLAY MODE."

CONSTANT.MSG_ENTER_NEW_VAULT = "ENTER NEW VAULT PATH: "

CONSTANT.MSG_VAULT_OPEN = "OPENED VAULT: "
CONSTANT.MSG_NO_VAULT = "THERE ARE NO VAULTS TO OPEN."
CONSTANT.MSG_NO_VAULT_DELETE = "THERE ARE NO VAULTS TO OPEN."
CONSTANT.MSG_NO_VAULT_MODIFY = "THERE ARE NO VAULTS TO MODIFY."

-- FILES
CONSTANT.MSG_NO_FILES = "THERE ARE NO FILES TO OPEN."
CONSTANT.MSG_INVALID_VAULT_SELECTED = "INVALID VAULT SELECTED FOR FILE MENU."
CONSTANT.FILE_SORT_NAME = "[S] SORT: FILE NAME"
CONSTANT.FILE_SORT_UPDATED = "[S] SORT: LAST UPDATED"
CONSTANT.FILE_INSTRUCTIONS_1 = ">> [J] [K] TO NAVIGATE. [ENTER] TO OPEN FILE. [Q] TO QUIT."
CONSTANT.FILE_INSTRUCTIONS_2 = ">> [N] TO OPEN NOTES FOR THE SELECTED FILE."
CONSTANT.FILE_INSTRUCTIONS_3 = ">> [C] TO CREATE NEW FILE."
CONSTANT.FILE_INSTRUCTIONS_4 = ">> [M] TO MODIFY FILE PATH."
CONSTANT.FILE_INSTRUCTIONS_5 = ">> [D] TO DELETE FILE."
CONSTANT.FILE_INSTRUCTIONS_6 = ">> [S] TO TOGGLE SORT MODES, [H] TO TOGGLE DISPLAY MODE."
CONSTANT.CREATE_NEW_FILE = "ENTER NEW FILE PATH (RELATIVE TO VAULT): "
CONSTANT.MSG_NO_FILES_MODIFY = "THERE ARE NO FILES TO MODIFY."
CONSTANT.MSG_NO_FILES_DELETE = "THERE ARE NO FILES TO DELETE."
CONSTANT.MSG_PARENT_VAULT_EXIST = "PARENT VAULT NO LONGER EXISTS!"

-- NOTES
CONSTANT.MSG_INVALID_NOTE_PATH = "INVALID VAULT OR FILE ENTRY FOR NOTES MENU."
CONSTANT.MSG_NOTES_EDITOR_CLOSED = "NOTES EDITOR WINDOW CLOSED."
CONSTANT.MSG_NOTES_EDITOR_INVALID = "NOTES EDITOR WINDOW NOT VALID OR ALREADY CLOSED"
CONSTANT.MSG_EDITOR_ATTEMPT = "NOTES EDITOR BUFFER IS INVALID. SKIPPING SAVE."
CONSTANT.MSG_NOTES_NOT_SAVED = "COULD NOT FIND THE TARGET FILE ENTRY IN VAULT DATA (after re-location). NOTES NOT SAVED."
CONSTANT.MSG_ATTEMPT_SAVE_NOTES = "ATTEMPTING TO SAVE NOTES AND CLOSE TERMINAL."
CONSTANT.NOTES_SORT_NAME = "[S] SORT: FILE NAME"
CONSTANT.NOTES_SORT_UPDATED = "[S] SORT: LAST UPDATED"
CONSTANT.NOTES_INSTRUCTIONS_1 = ">> USE [J] [K] TO NAVIGATE."
CONSTANT.NOTES_INSTRUCTIONS_2 = ">> [ENTER] TO OPEN NOTE OF FILE."
CONSTANT.NOTES_INSTRUCTIONS_3 = ">> [Q] TO QUIT."



-- Error Messages
CONSTANT.ERROR_MSG_FILE_NOT_FOUND = CONSTANT.FILE_NAME .. " not found in users home directory (" .. CONSTANT.FILE_PATH .. CONSTANT.FILE_NAME .. ")"
CONSTANT.ERROR_WRITE_OPERATION = "ERROR DURING WRITE OPERATION: "
CONSTANT.ERROR_INVALID_DIR_PATH = "ERROR: INVALID DIRECTORY PATH"
CONSTANT.ERROR_JSON_WRITING = "Error: Could not open JSON file for writing: "
CONSTANT.ERROR_NIL_JSON = "Error: Could not encode JSON data. JSON string is nil."
CONSTANT.UNKNOWN_ERROR = "UNKNOWN ERROR"
CONSTANT.INVALID_VAULT_NUMBER_ERROR = "INVALID VAULT NUMBER PROVIDED. PLEASE USE A NUMBER."


return CONSTANT
